In [3]:
import mxnet as mx
import ROOT as rt
import numpy as np
import math

import datetime

Welcome to JupyROOT 6.10/00


In [3]:
start=datetime.datetime.now()

jetset=[]
labels=[]
maxx=0.4
maxy=0.4                  
arnum=16
dx=0
bx=2*maxx/(2*arnum+1)
by=2*maxy/(2*arnum+1)
read=rt.TFile('jet2.root')
#record=mx.recordio.MXIndexedRecordIO('tmptlb.idx','tmptlb.rec','w')
record=mx.recordio.MXRecordIO('tmptdb.rec','w')
jet=rt.gDirectory.Get('jetAnalyser/jetAnalyser')
entries=jet.GetEntriesFast()
overlap=np.zeros(shape=(3,2*arnum+1,2*arnum+1))

for ent in range(entries):
    #if ent>1000:
    #    break
    jet.GetEntry(ent)
    #if jet.pt<300 or jet.pt>400:
        #continue
    if jet.partonId==0:
        continue
    palet=np.zeros(shape=(3,2*arnum+1,2*arnum+1),dtype=np.float16)
    r=0
    g=0
    b=0
    for i in range(len(jet.dau_pt)):
        x=int(math.floor((jet.dau_deta[i]/bx)+0.5)+arnum)
        if x<0 or x>2*arnum:
            continue
        y=int(math.floor((jet.dau_dphi[i]/by)+0.5)+arnum)
        if y<0 or y>2*arnum:
            continue
        pt=jet.dau_pt[i]
        if jet.dau_charge[i]==0:
            palet[1][x][y]+=pt

            if palet[1][x][y]>g:
                g=palet[1][x][y]
        else:
            palet[0][x][y]+=pt
            palet[2][x][y]+=1

            if palet[0][x][y]>r:
                r=palet[0][x][y]
            if palet[2][x][y]>b:
                b=palet[2][x][y]
            #pass
    #record.write(palet)
    for i in range(2*arnum+1):
        for j in range(2*arnum+1):
            if r!=0:
                palet[0][i][j]=255*palet[0][i][j]/r
            if g!=0:
                palet[1][i][j]=255*palet[1][i][j]/g
            if b!=0:
                palet[2][i][j]=255*palet[2][i][j]/b
    
    jetset.append(palet)
    """if (ent%1000==0):
        jetset=np.array(jetset,dtype=np.uint8)
        for l in range(len(jetset)):
            #record.write_idx(dx,str(jetset[l].tolist()))
            record.write(str(jetset[l].tolist()))
            dx+=1
        jetset=[]"""
    if jet.partonId==21:
        labels.append(1)

    else:
        labels.append(0)

    overlap=np.add(overlap,palet)
    
    
jetset=np.array(jetset,dtype=np.uint8)
for l in range(len(jetset)):
    record.write(str(jetset[l].tolist()))
    #record.write_idx(dx,str(jetset[l].tolist()))
    dx+=1
[r,g,b]=[0,0,0]
[gr,gg,gb]=[0,0,0]
[qr,qg,qb]=[0,0,0]
for i in range(2*arnum+1):
        for j in range(2*arnum+1):
            if overlap[0][i][j]>r:
                r=overlap[0][i][j]
            if overlap[1][i][j]>g:
                g=overlap[1][i][j]
            if overlap[2][i][j]>b:
                b=overlap[2][i][j]
                
for i in range(2*arnum+1):
        for j in range(2*arnum+1):
            if r!=0:
                overlap[0][i][j]=overlap[0][i][j]/r
            if g!=0:
                overlap[1][i][j]=overlap[1][i][j]/g
            if b!=0:
                overlap[2][i][j]=overlap[2][i][j]/b

record.close()
labels=np.array(labels)
###jetset=np.array(jetset,dtype=np.uint8)
###print jetset.shape
###data=jetset.reshape((len(jetset),3*33*33))
print datetime.datetime.now()-start

0:03:16.627497


In [13]:
jetset.shape

(14948, 3, 33, 33)

In [ ]:
0:04:22.827886
        0:03:52.983626
start=datetime.datetime.now()
record=mx.recordio.MXIndexedRecordIO('tmpl.idx','tmpl.rec','w')
j=0
for i in data[:]:
    record.write_idx(j,str(i.tolist()))
    j+=1
record.close()

print datetime.datetime.now()-start

In [10]:
record = mx.recordio.MXRecordIO('tmptlb.rec','r')

In [11]:
dx=0
while True:
    item=record.read()
    if not item:
        print dx
        break
    dx+=1

14948


In [19]:
np.uint8(jetset[1][1][16][:])

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,  12,   0, 255,   0,   0,   0,   0,   0,   2,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0], dtype=uint8)

In [53]:
start=datetime.datetime.now()
for i in data:
    if(eval(str(tuple(i)))!=tuple(i)):
        print "b"
        break
print datetime.datetime.now()-start


0:00:05.532844


In [52]:
start=datetime.datetime.now()
j=0
for i in data:
    if(eval(str(i.tolist()))!=i.tolist()):
        print j
        break
    j+=1
print datetime.datetime.now()-start


0:00:03.899646


In [178]:
start=datetime.datetime.now()
record=mx.recordio.MXRecordIO('tmpt.rec','w')
for i in data[:]:
    record.write(str(tuple(i)))
record.close()
print datetime.datetime.now()-start

0:00:47.633305


In [184]:
start=datetime.datetime.now()
record=mx.recordio.MXRecordIO('tmpt.rec','r')
j=0
while True:
    item = record.read()
    if not item:
        break
    if(eval(item)!=tuple(data[j])):
        print j
        break
    j+=1
record.close()
print j,datetime.datetime.now()-start

14948 0:01:08.726526


In [21]:
start=datetime.datetime.now()
record=mx.recordio.MXIndexedRecordIO('tmpl.idx','tmpl.rec','w')
j=0
for i in data[:]:
    record.write_idx(j,str(i.tolist()))
    j+=1
record.close()

print datetime.datetime.now()-start

0:00:03.013569


In [183]:
start=datetime.datetime.now()
record=mx.recordio.MXRecordIO('tmpl.rec','r')
j=0
while True:
    item = record.read()
    if not item:
        break
    if(eval(item)!=data[j].tolist()):
        print j
        break
    j+=1
record.close()
print j,datetime.datetime.now()-start

14948 0:01:06.879232


In [ ]:
start=datetime.datetime.now()
record=mx.recordio.MXRecordIO('tmpl.rec','w')
for i in len(labels):
    header=mx.recordio.IRHeader(0,labels[i],123,0)
    record.write(str(data[i].tolist()))
record.close()
print datetime.datetime.now()-start

In [ ]:
header=mx.recordio.IRHeader(0,labels[1],123,0)
packed=mx.recordio.pack_img(header,np.array([[[23,27,45],[28,32,50],[36,40,59],[35,39,58]],[[91,92,113],[97,98,119],[168,169,167],[166,167,165]]]))

In [15]:
np.array([[[23,27,45],[28,32,50],[36,40,59],[35,39,58]],[[91,92,113],[97,98,119],[168,169,167],[166,167,165]]])

array([[[ 23,  27,  45],
        [ 28,  32,  50],
        [ 36,  40,  59],
        [ 35,  39,  58]],

       [[ 91,  92, 113],
        [ 97,  98, 119],
        [168, 169, 167],
        [166, 167, 165]]])

In [4]:
import os
os.system("ls -alh")

0

total 555M
drwxr-xr-x 5 root root 4.0K Jul 12 07:02 .
drwxr-xr-x 1 root root 4.0K Jun 21 06:06 ..
drwxr-xr-x 8 root root 4.0K Jun 29 12:26 .git
drwxr-xr-x 2 root root 4.0K Jul 11 06:12 .ipynb_checkpoints
drwxr-xr-x 4 root root 4.0K Jul 10 06:38 data
-rw-r--r-- 1 root root 7.4K Jul 11 04:00 data.csv
-rw-r--r-- 1 root root 433K Jul 11 06:14 data_python.ipynb
-rw-r--r-- 1 root root  13K Jul 12 06:58 dataiter.ipynb
-rw-r--r-- 1 root root  22K Jul 12 06:58 datamakebot.ipynb
-rw-r--r-- 1 root root 100K Jun 21 06:05 jet run-Copy1.ipynb
-rwxr-xr-x 1 root root  24M May 31 07:15 jet2.root
-rw-r--r-- 1 root root 173K Jun 21 06:05 jetrun-Copy1.ipynb
-rw-r--r-- 1 root root 200K Jun 21 06:05 jetrun-Copy2.ipynb
-rw-r--r-- 1 root root 130K Jul 12 07:02 jetrun.ipynb
-rw-r--r-- 1 root root  14K Jun 21 06:05 mnist_python-Copy1.ipynb
-rwxr-xr-x 1 root root  20K Jun 21 06:05 mnist_python.ipynb
-rw-r--r-- 1 root root  696 Jul 10 06:43 tmp.idx
-rw-r--r-- 1 root root    0 Jul 12 06:58 tmp.rec
-rw-r--r-- 1 roo

In [15]:
eval(str([[1,23,4],[3,4]]))

[[1, 23, 4], [3, 4]]

In [5]:
import numpy as np
a=np.uint8([1.1123,3.555])

In [26]:
print ("< - - - - - - - - - - >")
print "<",
print "-",

< - - - - - - - - - - >
< -


In [5]:
import time
import sys
start=datetime.datetime.now()
for i in range(100):
    time.sleep(0.1)
    if(i!=0):
        sys.stdout.write("\r%d%%\t time remain %s" % (i ,str((100-i)*(datetime.datetime.now()-start)/i)))
    sys.stdout.flush()

99%	 time remain 0:00:00.102558

In [25]:
start=datetime.datetime.now()

In [9]:
import datetime
bbb= (100-int(100*ent/entries))(datetime.datetime.now()-start)/(int(100*ent/entries))

In [117]:
rt.string("tree")

'tree'

In [12]:
import ROOT as rt
tree = rt.TTree( 'treename', 'mytree' )
s = rt.string()
tree.Branch('mystr',s)
for word in ['hello','crue8kl','world']:
   s.replace(0, rt.string.npos, word)
   #s=rt.string(word)
   tree.Fill()
tree.Print()

******************************************************************************
*Tree    :treename  : mytree                                                 *
*Entries :        3 : Total =            1024 bytes  File  Size =          0 *
*        :          : Tree compression factor =   1.00                       *
******************************************************************************
*Br    0 :mystr     : string                                                 *
*Entries :        3 : Total  Size=        682 bytes  One basket in memory    *
*Baskets :        0 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*


In [11]:
tree.mystr

'hello'

In [13]:
import ROOT
import numpy as np
f = ROOT.TFile("tree.root", "recreate")
t = ROOT.TTree("name_of_tree", "tree title")


# create 1 dimensional float arrays (python's float datatype corresponds to c++ doubles)
# as fill variables
n = np.zeros(2, dtype=float)
u = np.zeros(2, dtype=float)

# create the branches and assign the fill-variables to them
t.Branch('norm', n, 'normal/string')
t.Branch('uniform', u, 'uniform/D')

# create some random numbers, fill them into the fill varibles and call Fill()
for i in xrange(100000):
	n[0] = ROOT.gRandom.Gaus()
	n[1] = ROOT.gRandom.Uniform()
	u[0] = ROOT.gRandom.Uniform()
	t.Fill()

# write the tree into the output file and close the file
f.Write()
f.Close()

Warning in <TBranch::TBranch>: Extra characters after type tag 'string' for branch 'norm'; must be one character.


In [51]:
read=rt.TFile('tree.root')
jet=rt.gDirectory.Get('name_of_tree')
entries=jet.GetEntriesFast()

In [19]:
read=rt.TFile('treett.root')
jet=rt.gDirectory.Get('imgset')

In [21]:
read.ls()

TFile**		treett.root	
 TFile*		treett.root	


In [40]:
jet.GetEntry(8)

16

In [52]:
jet.nor

0.0

In [42]:
np.zeros(2, dtype=float)

array([ 0.,  0.])

In [53]:
jet.Print()

******************************************************************************
*Tree    :name_of_tree: tree title                                             *
*Entries :   100000 : Total =         1204930 bytes  File  Size =     900268 *
*        :          : Tree compression factor =   1.34                       *
******************************************************************************
*Br    0 :norm      : Float_t vector<float>                                  *
*Entries :   100000 : Total  Size=     401602 bytes  File Size  =     353685 *
*Baskets :       13 : Basket Size=      32000 bytes  Compression=   1.13     *
*............................................................................*
*Br    1 :uniform   : uniform/D                                              *
*Entries :   100000 : Total  Size=     802962 bytes  File Size  =     545678 *
*Baskets :       26 : Basket Size=      32000 bytes  Compression=   1.47     *
*.................................................

In [96]:
a=rt.vector("float")()

In [97]:
for i in range(10):
    a.push_back(i)

In [105]:
b=rt.vector(rt.vector('float'))()

In [106]:
for i in range(10):
    b.push_back(i)

TypeError: none of the 2 overloaded methods succeeded. Full details:
  void vector<vector<float> >::push_back(const vector<float>& __x) =>
    could not convert argument 1
  void vector<vector<float> >::push_back(vector<float>&& __x) =>
    could not convert argument 1 (this method can not (yet) be called)